---
resources:
  - name: go-tumbo-git
    type: git
    icon: github
    source:
      uri: https://github.com/sahlinet/go-tumbo.git

  - name: golang-1.14.x-image
    type: registry-image
    icon: docker
    source:
      repository: golang
      tag: 1.14-stretch

task-config: &task-config
  platform: linux
  inputs:
    - name: go-tumbo-git
      path: go/src/github.com/sahlinet/go-tumbo
  params:
    GO111MODULE: "on"

task-config: &task-config
  platform: linux
  inputs:
    - name: go-tumbo-git
      path: go/src/github.com/sahlinet/go-tumbo
  params:
    GO111MODULE: "on"
  run:
    path: /bin/sh
    args:
      - -c
      - |
        GOPATH=$PWD/go

        cd go/src/github.com/sahlinet/go-tumbo

        go vet ./...
        go test -v ./...


jobs:
  - name: unittest
    public: true
    plan:
      - get: go-tumbo-git
        trigger: true
      - get: golang-1.14.x-image
        trigger: true

      - task: run-tests
        image: golang-1.14.x-image
        config:
          << : *task-config
          run:
            path: /bin/sh
            args:
              - -c
              - |
                GOPATH=$PWD/go
                cd go/src/github.com/sahlinet/go-tumbo
                go vet ./...
                go test -v ./...
  - name: build
    public: true
    plan:
      - get: go-tumbo-git
        trigger: true
      - get: golang-1.14.x-image
        trigger: true

      - task: build-binary
        image: golang-1.14.x-image
        config:
          << : *task-config
          run:
            path: /bin/sh
            args:
              - -c
              - |
                GOPATH=$PWD/go
                cd go/src/github.com/sahlinet/go-tumbo
                go build ./cmd/tumbo
